//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Daggen.SecurityRole.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Daggen.SecurityRole.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] ActorSecurityRoleReport {
            get {
                object obj = ResourceManager.GetObject("ActorSecurityRoleReport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap analytic_report {
            get {
                object obj = ResourceManager.GetObject("analytic-report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select where to save the files..
        /// </summary>
        internal static string Controller_button2_Click_Select_where_to_save_the_files_ {
            get {
                return ResourceManager.GetString("Controller_button2_Click_Select_where_to_save_the_files_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to add selected security roles to enabled users/teams?.
        /// </summary>
        internal static string Controller_buttonAddRole_Click_Confirm_Add_Roles_To_Actors {
            get {
                return ResourceManager.GetString("Controller_buttonAddRole_Click_Confirm_Add_Roles_To_Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Modification.
        /// </summary>
        internal static string Controller_buttonAddRole_Click_Confirm_Modification {
            get {
                return ResourceManager.GetString("Controller_buttonAddRole_Click_Confirm_Modification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to remove selected security roles from enabled users/teams?.
        /// </summary>
        internal static string Controller_buttonRemoveRole_Click_Confirm_Remove_Roles_To_Actors {
            get {
                return ResourceManager.GetString("Controller_buttonRemoveRole_Click_Confirm_Remove_Roles_To_Actors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report is now saved.
        /// </summary>
        internal static string Controller_toolStripButton1_Click_Report_is_now_saved {
            get {
                return ResourceManager.GetString("Controller_toolStripButton1_Click_Report_is_now_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh_button {
            get {
                object obj = ResourceManager.GetObject("refresh-button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check any line before pressing this button..
        /// </summary>
        internal static string WarningOnEmptySelection {
            get {
                return ResourceManager.GetString("WarningOnEmptySelection", resourceCulture);
            }
        }
    }
}
